### ISSUE TITLE
Báo cáo tiến độ training 11/11/2015

### ISSUE THREAD

**Issue by anhtuanqn1002** [anhtuanqn1002/MyLocations#2]
Hi anh,
#### New project

Tạo project và làm quen với Tab Bar Controller
#### Core Location

Các bước sử dụng Core Location framework

> 1: Add framework (vào project setting —> Linked framework and libraries—> (+) —> Chọn framework
> 2: Import vào file .h
> 3: Adopt protocol: <CLLocationManagerDelegate>
> 4: Khai báo 1 thuộc tính CLLocation *_locationManager. Đối tượng này sẽ là cái giữ toạ độ GPS
> 5: Khởi tạo _locationManager trong method initWithCoder (nhớ kiểm tra self = [super initWithCoder:aDecoder]). Chỉ là khởi tạo mà thôi. Muốn nhận toạ độ thì phải gọi method startUpdatingLocation trước. Mỗi khi muốn cập nhật toạ độ thì gọi phương thức này (nếu không nhờ phương thức này thì việc cập nhật diễn ra liên tục và sẽ làm tốn pin).
> 6: Khi có lệnh gọi việc lấy toạ độ (chẳng hạn bấm button) thì:
>      \* set delegate của _locationManager = self
>      \* Định dạng độ chính xác cho việc lấy vị trí thông qua _locationManager.desiredAccuracy.
>      \* Gọi startUpdatingLocation.

Method -(void)locationManager:(CLLocationManager *)manager didFailWithError:(nonnull NSError *)error: nếu tắt dịch vụ location, method này sẽ được chạy (báo dịch vụ location tắt)
NSError có 1 “domain” và 1 “code”. Trong trường hợp này “code == 1” tức là không cho phép dùng location services.
#### Putting the coordinates on the screen

method locationManager:didUpdateLocations: không vào được, nó không lấy được GPS.
#### Handling errors

Property horizontalAccuracy, desiredAccuracy chưa hiểu cách biểu diễn của nó thế nào? 
#### Improving the results

set title và trạng thái button thông qua method setTitle:forState:

Đọc hiểu thì tới đây, nhưng mà test ứng dụng chưa được nên hơi nản và mất thời gian. Vì thế mà hôm nay chưa xong được mấy phần đề ra. Hiện còn 2 mục là Reverse geocoding và Testing in practice. Thời gian em dự tính là 2 giờ để học 2 phần này. Ngày mai, trước tiên là fix cái lỗi không lấy được GPS coordinates. Tiếp theo là phần Objects vs Classes:

> - Inheritance 
> - Overriding methods 
> - Protected instance variables 
> - Casts 
> - The “id” type

**Comment by tungtx90** [comment]
> Property horizontalAccuracy, desiredAccuracy chưa hiểu cách biểu diễn của nó thế nào?

Em coi ở đây nhé
https://developer.apple.com/library/ios/documentation/CoreLocation/Reference/CLLocation_Class/

**Comment by tungtx90** [comment]
Phần này em xem lại chưa? :)

**Comment by anhtuanqn1002** [comment]
desiredAccuracy em hiểu là độ chính xác mong muốn, nghĩa là nếu như di chuyển không quá khoảng cách desiredAccuracy thì nó sẽ không cập nhật địa điểm mới. Còn cái horizontal và vertical Accuracy nó liên quan tới độ cao so với mực nước biển, nhưng không hiểu nó tính sao lắm, e dịch rồi mà k hiểu lắm a. Hiểu là dùng chúng để xác định khoảng cách sẽ cập nhật vị trí mới (quá khoảng cách này thì mới cập nhật), nhưng mà không hiểu cách tính. E hiểu vậy đúng không a.

**Comment by tungtx90** [comment]
- `Desired Accuracy` là độ chính xác: kết quả nó sẽ trả về cho em chính xác đến mức nào. Em xem thêm ở đây: https://developer.apple.com/library/ios/documentation/CoreLocation/Reference/CLLocationManager_Class/#//apple_ref/occ/instp/CLLocationManager/desiredAccuracy
- Nếu em muốn xác định khi device di chuyển khoảng cách bao nhiêu là sẽ cập nhật lại vị trí cho em thì em phải dùng cái `distanceFilter` (tính theo phương ngang), tức là khi di chuyển theo chiều cao (lên cao) sẽ không tính. Xem ở đây: http://stackoverflow.com/questions/5930612/how-to-set-accuracy-and-distance-filter-when-using-mkmapview
- `horizontal Accuracy`: độ chính xác theo chiều ngang. Kinh độ vĩ độ sẽ xác định 1 điểm trên trái đất, em coi nói là tâm đường tròn đi, cái này sẽ là bán kính của đường tròn đó.
- `vertical Accuracy`: độ chính xác về cao độ.
  Horizontal va vertical là dữ liệu `readonly`. Tức là khi lấy được dữ liệu về toạ độ, và dữ liệu này sẽ gồm những thông tin về độ chính xác như trên

**Comment by anhtuanqn1002** [comment]
# OK rồi anh :dancer:
