### ISSUE TITLE
Báo cáo tiến độ training 12/11/2015

### ISSUE THREAD

**Issue by anhtuanqn1002** [anhtuanqn1002/MyLocations#3]
## Objects vs. Classes
- Inheritance
- Overriding methods
- Protected instance variables
- Casts
- The “id” type
#### Protected instance variables

Sử dụng @protected để cho phép lớp con kế thừa được phép sử dụng thuộc tính đó. Như vậy thuộc tính đó nếu khai báo bình thường như NSInteger _sohang; thì lớp con không thể sử dụng nó.
#### Casts

Cái này nó giống như là tính đa hình đúng không anh. Class cha là 1 kiểu Pet, các class kế thừa nó là Dog và Cat thì khi khai báo 1 đối tượng kiểu Pet sẽ có thể tạo và nó có thể chứa kiểu Dog hoặc Cat đúng không anh. 
Đọc xuống dưới thì casts này lại giống như ép kiểu hơn.
#### The “id” type

Theo tài liệu nói thì id là 1 đối tượng. Không biết đúng không anh. Nó đặc biệt và sử dụng nó thì không dùng dấu \* vào. Nó có nghĩa là một đối tượng bất kì. Không quan tâm tới cái gì truyền vào cho nó hay trả về. NSObject là một đối tượng tổng quát. Vậy dùng id và NSObject có nhiều khác biệt không anh.
#### The Tag Location screen
- Design 
- Making the cells 
- Putting the location info into the screen 
- The description text view 
- The category picker 
#### Improving the user experience
- The HUD
- The object graph
- Life and death of objects
- Copy and assign properties 
- Manual memory management

**Comment by tungtx90** [comment]
> Casts
> 
> Cái này nó giống như là tính đa hình đúng không anh. Class cha là 1 kiểu Pet, các class kế thừa nó là >Dog và Cat thì khi khai báo 1 đối tượng kiểu Pet sẽ có thể tạo và nó có thể chứa kiểu Dog hoặc Cat >đúng không anh. 
> Đọc xuống dưới thì casts này lại giống như ép kiểu hơn.

Đúng rồi em. Em nhớ thêm chi tiết này, con trỏ đến class cha ko thể nào cast về kiểu của class con, nhưng ngược lại thì được.

---

> The “id” type

"id" là 1 con trỏ nó trỏ đến bất kỳ kiểu dữ liệu nào. Em có thể hiểu nó có thể là bất kỳ kiểu dữ liệu nào. Nó tổng quát hơn cả NSObject.

**Comment by anhtuanqn1002** [comment]
> Đúng rồi em. Em nhớ thêm chi tiết này, con trỏ đến class cha ko thể nào cast về kiểu của class con, nhưng ngược lại thì được.

Anh lấy ví dụ cho em hiểu được không anh :+1:

**Comment by tungtx90** [comment]
Có 2 class:
Class A, Class B thừa kế A

```
A *ptA = [[A alloc] init];
B *ptB = (B*)ptA; --> `fail` vì không thể cast instance của A(parent) về B(child). Hay nói cách khác là ko thể dùng con trỏ kiểu B để trỏ về vùng nhớ kiểu A
```

---

```
B *ptB = [[B alloc] init];
A *ptA = ptB; --> `ok` 
```
